---
title: 국가데이터
author: Baek, wonhee
date: '2020-06-17'
output: 
   blogdown::html_page:
    toc: yes
    toc_float: true
    highlight: tango
    code_folding: hide
    number_section: true
    self_contained: true
categories:
  - R
tags:
  - big data
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

PCA(Patient Controlled Analgesia)

- 어떤 방법이든, 어떤 루트로드 환자 스스로 진통제를 투여할 수 있는 자가 통증 조절법

- 장점
   - 환자 개개인간의   차이를 그복
   - 환자가 진통제를 요구한 후 실제 투여될 때까지의 시간 지연을 방지 
   
- 적응환 
   - 급성통증 조절이 필요한 환자 
   - oral medication을 사용할 수 없는 환자 
   - 의ᄉ 명료하고 PCA ᄉ  대해서 이해하고 잘 따를 수 있는 환자 
   - 환자가 스스로 진ᄐ제 투여하는 것을 거부하거나 투여할 수 없으면, 가족이나 간호사가 투여해 주는 방법으 사용할 수 있음

--- 

## 기본개ᄂ 

- Bolus dose(일회 주입량) : 환자가 버튼을 한번 누를 때마다 ᄐ 요구량 
- Basal infusion(지속 주입량) : Continuous infusion 이라고도 함. 환자가 버튼을 누르지 않아도 일정하ᄀ 지속 주입되는 용량
- Lock-out period(자 시간) : 요구량 투여 후 다음 요구량이 투여될 수 있는 시간 간격 

---

### 기본개념 

MEAC(Minimum effective analgesic concentration) 
   - 진통에 필요한 마약성 진통제의 최소 ᄂ 
   - 수술 후 initial dose를 투여하여 MEAC에 도달 조절 한 후 환자가 PCA를 사용하여 opioid의 혈중ᄂ MEAC 이상으로 유지 
   

## 자가통증조절기(PCA)

- 물 PCA 

- 기계식 PCA 

--- 

## PCA의 종류와 약제 

- IV PCA : 정  통해 PCA 연결

- Epidural PCA: 경맥 외강을 통해 PCA 연결 

- Nerve PCA: 신경 차단 PCA

---

## PCA의 부작용

- 마약 진통제의 부작용 

---

## 모니터링 
호흡수 등 
